---
q_states:
  q_list:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
  initial: '0'
  final: '6'

# Alfabeto de entrada
alphabet:
  - a
  - b

# Alfabeto de la cinta (incluye input + marcadores adicionales)
tape_alphabet:
  - a
  - b
  - X
  - 

# Función de transición
delta:

  # Estado 0
  - params:
      initial_state: '0'
      mem_cache_value:
      tape_input: a
    output:
      final_state: '0'
      mem_cache_value:
      tape_output: a
      tape_displacement: R

  - params:
      initial_state: '0'
      mem_cache_value:
      tape_input: b
    output:
      final_state: '0'
      mem_cache_value:
      tape_output: b
      tape_displacement: R

  - params:
      initial_state: '0'
      mem_cache_value:
      tape_input:
    output:
      final_state: '1'
      mem_cache_value:
      tape_output:
      tape_displacement: L

  # Estado 1
  - params:
      initial_state: '1'
      mem_cache_value:
      tape_input: X
    output:
      final_state: '1'
      mem_cache_value:
      tape_output: X
      tape_displacement: L

  - params:
      initial_state: '1'
      mem_cache_value:
      tape_input: a
    output:
      final_state: '2'
      mem_cache_value:
      tape_output: X
      tape_displacement: R

  - params:
      initial_state: '1'
      mem_cache_value:
      tape_input: b
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: X
      tape_displacement: R

  - params:
      initial_state: '1'
      mem_cache_value:
      tape_input:
    output:
      final_state: '5'
      mem_cache_value:
      tape_output:
      tape_displacement: R

  # Estado 2
  - params:
      initial_state: '2'
      mem_cache_value:
      tape_input: a
    output:
      final_state: '2'
      mem_cache_value:
      tape_output: a
      tape_displacement: R

  - params:
      initial_state: '2'
      mem_cache_value:
      tape_input: b
    output:
      final_state: '2'
      mem_cache_value:
      tape_output: b
      tape_displacement: R

  - params:
      initial_state: '2'
      mem_cache_value:
      tape_input: X
    output:
      final_state: '2'
      mem_cache_value:
      tape_output: X
      tape_displacement: R

  - params:
      initial_state: '2'
      mem_cache_value:
      tape_input:
    output:
      final_state: '4'
      mem_cache_value:
      tape_output: a
      tape_displacement: L

  # Estado 3
  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input: a
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: a
      tape_displacement: R

  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input: b
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: b
      tape_displacement: R

  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input: X
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: X
      tape_displacement: R

  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input:
    output:
      final_state: '4'
      mem_cache_value:
      tape_output: b
      tape_displacement: L

  # Estado 4
  - params:
      initial_state: '4'
      mem_cache_value:
      tape_input: a
    output:
      final_state: '4'
      mem_cache_value:
      tape_output: a
      tape_displacement: L

  - params:
      initial_state: '4'
      mem_cache_value:
      tape_input: b
    output:
      final_state: '4'
      mem_cache_value:
      tape_output: b
      tape_displacement: L

  - params:
      initial_state: '4'
      mem_cache_value:
      tape_input: X
    output:
      final_state: '1'
      mem_cache_value:
      tape_output: X
      tape_displacement: L

  # Estado 5
  - params:
      initial_state: '5'
      mem_cache_value:
      tape_input: X
    output:
      final_state: '5'
      mem_cache_value:
      tape_output:
      tape_displacement: R

  - params:
      initial_state: '5'
      mem_cache_value:
      tape_input: b
    output:
      final_state: '6'
      mem_cache_value:
      tape_output: b
      tape_displacement: S

  - params:
      initial_state: '5'
      mem_cache_value:
      tape_input: a
    output:
      final_state: '6'
      mem_cache_value:
      tape_output: a
      tape_displacement: S

# Cadenas a simular
simulation_strings:
  - aabbabab
  - abababab
  - aaaabbbb
  - aaabbbabab
