---
q_states:
  q_list:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
  initial: '0'
  final: '9'

# Alfabeto de entrada
alphabet:
  - '1'

# Alfabeto de la cinta (incluye input + marcadores adicionales)
tape_alphabet:
  - '1'
  - Z
  - A
  - B
  - C
  - X
  - Y
  - 

# Función de transición
delta:

  # Estado 0
  - params:
      initial_state: '0'
      mem_cache_value:
      tape_input: '1'
    output:
      final_state: '1'
      mem_cache_value:
      tape_output:
      tape_displacement: R

  - params:
      initial_state: '0'
      mem_cache_value:
      tape_input: Z
    output:
      final_state: '8'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: R

  # Estado 1
  - params:
      initial_state: '1'
      mem_cache_value:
      tape_input:
    output:
      final_state: '0'
      mem_cache_value:
      tape_output: Z
      tape_displacement: S

  - params:
      initial_state: '1'
      mem_cache_value:
      tape_input: Z
    output:
      final_state: '0'
      mem_cache_value:
      tape_output: Z
      tape_displacement: S

  - params:
      initial_state: '1'
      mem_cache_value:
      tape_input: '1'
    output:
      final_state: '2'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: R

  # Estado 2
  - params:
      initial_state: '2'
      mem_cache_value:
      tape_input: '1'
    output:
      final_state: '2'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: R

  - params:
      initial_state: '2'
      mem_cache_value:
      tape_input:
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: Z
      tape_displacement: L

  - params:
      initial_state: '2'
      mem_cache_value:
      tape_input: Z
    output:
      final_state: '4'
      mem_cache_value:
      tape_output: Z
      tape_displacement: R

  # Estado 3
  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input: Z
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: Z
      tape_displacement: L

  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input: '1'
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: L

  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input: A
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: A
      tape_displacement: L

  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input: B
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: B
      tape_displacement: L

  - params:
      initial_state: '3'
      mem_cache_value:
      tape_input:
    output:
      final_state: '0'
      mem_cache_value:
      tape_output:
      tape_displacement: R

  # Estado 4
  - params:
      initial_state: '4'
      mem_cache_value:
      tape_input:
    output:
      final_state: '3'
      mem_cache_value:
      tape_output: B
      tape_displacement: L

  - params:
      initial_state: '4'
      mem_cache_value:
      tape_input: '1'
    output:
      final_state: '4'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: R

  - params:
      initial_state: '4'
      mem_cache_value:
      tape_input: A
    output:
      final_state: '6'
      mem_cache_value:
      tape_output: X
      tape_displacement: R

  - params:
      initial_state: '4'
      mem_cache_value:
      tape_input: B
    output:
      final_state: '6'
      mem_cache_value:
      tape_output: Y
      tape_displacement: R

  - params:
      initial_state: '4'
      mem_cache_value:
      tape_input: C
    output:
      final_state: '5'
      mem_cache_value:
      tape_output: B
      tape_displacement: R

  # Estado 5
  - params:
      initial_state: '5'
      mem_cache_value:
      tape_input: C
    output:
      final_state: '5'
      mem_cache_value:
      tape_output: B
      tape_displacement: R

  - params:
      initial_state: '5'
      mem_cache_value:
      tape_input:
    output:
      final_state: '3'
      mem_cache_value:
      tape_output:
      tape_displacement: L

  # Estado 6
  - params:
      initial_state: '6'
      mem_cache_value:
      tape_input: A
    output:
      final_state: '6'
      mem_cache_value:
      tape_output: A
      tape_displacement: R

  - params:
      initial_state: '6'
      mem_cache_value:
      tape_input: B
    output:
      final_state: '6'
      mem_cache_value:
      tape_output: B
      tape_displacement: R

  - params:
      initial_state: '6'
      mem_cache_value:
      tape_input: C
    output:
      final_state: '6'
      mem_cache_value:
      tape_output: C
      tape_displacement: R

  - params:
      initial_state: '6'
      mem_cache_value:
      tape_input:
    output:
      final_state: '7'
      mem_cache_value:
      tape_output: C
      tape_displacement: L

  # Estado 7
  - params:
      initial_state: '7'
      mem_cache_value:
      tape_input: A
    output:
      final_state: '7'
      mem_cache_value:
      tape_output: A
      tape_displacement: L

  - params:
      initial_state: '7'
      mem_cache_value:
      tape_input: B
    output:
      final_state: '7'
      mem_cache_value:
      tape_output: B
      tape_displacement: L

  - params:
      initial_state: '7'
      mem_cache_value:
      tape_input: C
    output:
      final_state: '7'
      mem_cache_value:
      tape_output: C
      tape_displacement: L

  - params:
      initial_state: '7'
      mem_cache_value:
      tape_input: X
    output:
      final_state: '4'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: R

  - params:
      initial_state: '7'
      mem_cache_value:
      tape_input: Y
    output:
      final_state: '4'
      mem_cache_value:
      tape_output: A
      tape_displacement: R

  # Estado 8
  - params:
      initial_state: '8'
      mem_cache_value:
      tape_input: '1'
    output:
      final_state: '8'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: R

  - params:
      initial_state: '8'
      mem_cache_value:
      tape_input: A
    output:
      final_state: '8'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: R

  - params:
      initial_state: '8'
      mem_cache_value:
      tape_input: B
    output:
      final_state: '8'
      mem_cache_value:
      tape_output: '1'
      tape_displacement: R

  - params:
      initial_state: '8'
      mem_cache_value:
      tape_input:
    output:
      final_state: '9'
      mem_cache_value:
      tape_output:
      tape_displacement: L

# Cadenas a simular
simulation_strings:
  - 1
  - 11
  - 111
  - 1111
  - 11111
  - 111111
